# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'carExpensesTracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for carExpensesTracker
  pod 'FirebaseAnalytics'
  pod 'Firebase/Firestore'
  pod 'FirebaseDatabase'
  pod 'Firebase/Storage'
  pod 'Firebase/Analytics'

  target 'carExpensesTrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'carExpensesTrackerUITests' do
    # Pods for testing
  end

end
